#!/usr/bin/env bash
set -euo pipefail

# Deploy Paperclip on a Yandex Cloud VM (or any Linux server with Docker).
#
# Usage:
#   ./scripts/yc-vm-setup.sh [options]
#
# Options:
#   --secret <val>        BETTER_AUTH_SECRET (generated if omitted)
#   --anthropic <key>     ANTHROPIC_API_KEY
#   --openai <key>        OPENAI_API_KEY
#   --port <port>         Host port to bind (default: 3100)
#   --data-dir <path>     Data directory (default: ./data/docker-paperclip)
#   --no-systemd          Skip systemd service setup
#   --restart             Restart existing deployment (skip prompts)
#
# Run from the paperclip repo root on the target VM.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Defaults ──────────────────────────────────────────────────────────────────
PORT="${PORT:-3100}"
DATA_DIR="${DATA_DIR:-$PROJECT_ROOT/data/docker-paperclip}"
SETUP_SYSTEMD=true
RESTART_MODE=false
SECRET=""
ANTHROPIC_KEY=""
OPENAI_KEY=""

# ── Colours ───────────────────────────────────────────────────────────────────
green()  { echo -e "\033[32m$*\033[0m"; }
yellow() { echo -e "\033[33m$*\033[0m"; }
red()    { echo -e "\033[31m$*\033[0m"; }
bold()   { echo -e "\033[1m$*\033[0m"; }
step()   { echo; bold "▶ $*"; }

# ── Parse args ────────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --secret)      SECRET="$2"; shift 2 ;;
    --anthropic)   ANTHROPIC_KEY="$2"; shift 2 ;;
    --openai)      OPENAI_KEY="$2"; shift 2 ;;
    --port)        PORT="$2"; shift 2 ;;
    --data-dir)    DATA_DIR="$2"; shift 2 ;;
    --no-systemd)  SETUP_SYSTEMD=false; shift ;;
    --restart)     RESTART_MODE=true; shift ;;
    *) red "Unknown option: $1"; exit 1 ;;
  esac
done

# ── Banner ────────────────────────────────────────────────────────────────────
echo
bold "╔═══════════════════════════════════════╗"
bold "║   Paperclip — Yandex Cloud VM Setup   ║"
bold "╚═══════════════════════════════════════╝"
echo

cd "$PROJECT_ROOT"

# ── 1. Check Docker ───────────────────────────────────────────────────────────
step "Checking Docker"
if ! command -v docker &>/dev/null; then
  red "Docker not found. Install it first: curl -fsSL https://get.docker.com | sudo sh"
  exit 1
fi

if ! docker compose version &>/dev/null; then
  yellow "Docker Compose plugin missing — installing..."
  sudo apt-get update -qq && sudo apt-get install -y docker-compose-plugin
fi

green "Docker $(docker --version | cut -d' ' -f3 | tr -d ',')"
green "Compose $(docker compose version --short)"

# ── 2. Generate / read .env ───────────────────────────────────────────────────
step "Configuring environment"

ENV_FILE="$PROJECT_ROOT/.env"

if [[ -f "$ENV_FILE" && "$RESTART_MODE" == "true" ]]; then
  green ".env already exists — keeping it (restart mode)"
else
  # Generate secret if not provided
  if [[ -z "$SECRET" ]]; then
    SECRET="$(openssl rand -hex 32)"
    yellow "Generated BETTER_AUTH_SECRET automatically"
  fi

  # Prompt for API keys if not provided and not in restart mode
  if [[ -z "$ANTHROPIC_KEY" && "$RESTART_MODE" == "false" ]]; then
    echo
    yellow "Enter your ANTHROPIC_API_KEY (sk-ant-...) or press Enter to skip:"
    read -r -s ANTHROPIC_KEY || true
  fi

  if [[ -z "$OPENAI_KEY" && "$RESTART_MODE" == "false" ]]; then
    yellow "Enter your OPENAI_API_KEY (sk-...) or press Enter to skip:"
    read -r -s OPENAI_KEY || true
  fi

  cat > "$ENV_FILE" << EOF
# Paperclip — generated by yc-vm-setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
BETTER_AUTH_SECRET=${SECRET}
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}
OPENAI_API_KEY=${OPENAI_KEY}
PAPERCLIP_PORT=${PORT}
PAPERCLIP_DATA_DIR=${DATA_DIR}
PAPERCLIP_PUBLIC_URL=http://localhost:${PORT}
EOF

  chmod 600 "$ENV_FILE"
  green ".env written to $ENV_FILE"
fi

# ── 3. Create data directory ──────────────────────────────────────────────────
step "Preparing data directory"
mkdir -p "$DATA_DIR"
green "Data directory: $DATA_DIR"

# ── 4. Build and start ────────────────────────────────────────────────────────
step "Building and starting Paperclip"
set -o allexport
# shellcheck source=/dev/null
source "$ENV_FILE"
set +o allexport

docker compose -f "$PROJECT_ROOT/docker-compose.quickstart.yml" up -d --build

# ── 5. Wait for health ────────────────────────────────────────────────────────
step "Waiting for server to be healthy"
HEALTHY=false
for i in $(seq 1 30); do
  if curl -sf "http://localhost:${PORT}/api/health" &>/dev/null; then
    HEALTHY=true
    break
  fi
  echo -n "."
  sleep 2
done
echo

if [[ "$HEALTHY" == "true" ]]; then
  green "Server is healthy at http://localhost:${PORT}"
else
  yellow "Server not responding yet — check logs:"
  yellow "  docker compose -f docker-compose.quickstart.yml logs -f"
fi

# ── 6. systemd service ────────────────────────────────────────────────────────
if [[ "$SETUP_SYSTEMD" == "true" ]]; then
  step "Setting up systemd service (auto-start on reboot)"

  SERVICE_FILE="/etc/systemd/system/paperclip.service"
  CURRENT_USER="$(whoami)"

  sudo tee "$SERVICE_FILE" > /dev/null << EOF
[Unit]
Description=Paperclip AI Orchestrator
After=docker.service
Requires=docker.service

[Service]
Type=simple
WorkingDirectory=${PROJECT_ROOT}
EnvironmentFile=${ENV_FILE}
ExecStart=/usr/bin/docker compose -f ${PROJECT_ROOT}/docker-compose.quickstart.yml up
ExecStop=/usr/bin/docker compose -f ${PROJECT_ROOT}/docker-compose.quickstart.yml down
Restart=on-failure
RestartSec=10
User=${CURRENT_USER}

[Install]
WantedBy=multi-user.target
EOF

  sudo systemctl daemon-reload
  sudo systemctl enable paperclip --quiet
  green "systemd service enabled: sudo systemctl status paperclip"
fi

# ── 7. Done ───────────────────────────────────────────────────────────────────
echo
bold "╔═══════════════════════════════════════╗"
bold "║          Setup complete!              ║"
bold "╚═══════════════════════════════════════╝"
echo
green "  Paperclip is running on this VM at http://localhost:${PORT}"
echo
bold "  Next step — open SSH tunnel from your local machine:"
echo "    ssh -N -L ${PORT}:localhost:${PORT} <user>@<VM_IP>"
echo "  Then open: http://localhost:${PORT}"
echo
bold "  Useful commands:"
echo "    docker compose -f docker-compose.quickstart.yml logs -f    # logs"
echo "    docker compose -f docker-compose.quickstart.yml ps         # status"
echo "    docker compose -f docker-compose.quickstart.yml restart    # restart"
echo "    sudo systemctl status paperclip                            # systemd"
echo
